_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.13
        t:
            "3":
                - 2
                - 16
                - 55
            "4": 3.11.13
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
architecture:
    value: CNN
dataset:
    value: CIFAR-100
epochs:
    value: 10
learning_rate:
    value: 0.02
