# configs/model/original.yaml - Match original model exactly
_target_: src.models.neural_nets.SimpleNN

# Exact architecture from original
hidden_sizes: [50]
dropout_rate: 0.4
activation: "relu"

# Original used RMSprop, not Adam!
learning_rate: 0.001
optimizer: "rmsprop"  # ← KEY FIX: RMSprop like original
weight_decay: 0.0  # No weight decay in original
