# configs/training/default.yaml

# Training parameters
max_epochs: 50
patience: 10  # Early stopping patience
min_delta: 1.0  # Minimum change for early stopping

# Learning rate scheduling
lr_scheduler:
  name: "reduce_on_plateau"
  factor: 0.5
  patience: 5
  min_lr: 1e-6

# Validation
validation_split: 0.2
cross_validation:
  enabled: false
  n_folds: 5

# Logging
log_every_n_steps: 1
save_top_k: 3  # Save top 3 models

# Hardware
accelerator: "auto"  # "cpu", "gpu", "auto"
devices: 1
